geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path, re_path
app_name = 'adminapp'

urlpatterns = [
    #re_path('^users/read/$', adminapp.index, name='index'),
    re_path('^users/read/$', adminapp.UsersListView.as_view(), name='index'),
    re_path('^user/create/$', adminapp.user_create, name='user_create'),
    re_path('^user/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    re_path('^user/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),
    re_path('^categories/$', adminapp.categories, name='categories'),
    #re_path('^category/create/$', adminapp.category_create, name='category_create'),
    re_path('^category/create/$', adminapp.ProductCategoruCreateView.as_view(), name='category_create'),
    #re_path('^category/update/(?P<pk>\d+)/$', adminapp.category_update, name='category_update'),
    re_path('^category/update/(?P<pk>\d+)/$', adminapp.ProductCategoruUpdateView.as_view(), name='category_update'),
    #re_path('^category/delete/(?P<pk>\d+)/$', adminapp.category_delete, name='category_delete'),
    re_path('^category/delete/(?P<pk>\d+)/$', adminapp.ProductCategoruDeleteView.as_view(), name='category_delete'),
    re_path('^products/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
   # re_path('^product/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
re_path('^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
    re_path('^product/create/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path('^product/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path('^product/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
import authapp.views as authapp
from django.urls import path, re_path
app_name = 'authapp'

urlpatterns = [
    re_path('^login/$', authapp.userlogin, name='login'),
    re_path('^logout/$', authapp.userlogout, name='logout'),
    re_path('^register/$', authapp.user_register, name='register'),
    re_path('^update/$', authapp.user_update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/django2.0/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path, re_path
app_name = 'adminapp'

urlpatterns = [
    #re_path('^users/read/$', adminapp.index, name='index'),
    re_path('^users/read/$', adminapp.UsersListView.as_view(), name='index'),
    re_path('^user/create/$', adminapp.user_create, name='user_create'),
    re_path('^user/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    re_path('^user/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),
    re_path('^categories/$', adminapp.categories, name='categories'),
    #re_path('^category/create/$', adminapp.category_create, name='category_create'),
    re_path('^category/create/$', adminapp.ProductCategoruCreateView.as_view(), name='category_create'),
    #re_path('^category/update/(?P<pk>\d+)/$', adminapp.category_update, name='category_update'),
    re_path('^category/update/(?P<pk>\d+)/$', adminapp.ProductCategoruUpdateView.as_view(), name='category_update'),
    #re_path('^category/delete/(?P<pk>\d+)/$', adminapp.category_delete, name='category_delete'),
    re_path('^category/delete/(?P<pk>\d+)/$', adminapp.ProductCategoruDeleteView.as_view(), name='category_delete'),
    re_path('^products/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
   # re_path('^product/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
re_path('^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
    re_path('^product/create/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path('^product/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path('^product/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   # path('admin/', admin.site.urls),
    re_path('^', include('mainapp.urls', namespace='main')),
    re_path('^auth/', include('authapp.urls', namespace='auth')),
    re_path('^basket/', include('basketapp.urls', namespace='basket')),
    re_path('^myadmin/', include('adminapp.urls', namespace='admin')),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path('^orders/', include('ordersapp.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/django2.0/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from authapp.models import ShopUser
from mainapp.models import ProductCategoru, Product
import django.forms as forms


class AdminShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email',
                  'age')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы очень молоды!")
        return data

class AdminShopUserChangeForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password', 'email',
                  'age', 'avatar', 'is_active', 'is_staff', 'is_superuser')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

class AdminProductCategoruEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategoru
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            # field.help_text = ''

class AdminProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/django2.0/adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from authapp.models import ShopUser
from mainapp.models import ProductCategoru, Product
import django.forms as forms


class AdminShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email',
                  'age')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы очень молоды!")
        return data

class AdminShopUserChangeForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password', 'email',
                  'age', 'avatar', 'is_active', 'is_staff', 'is_superuser')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

class AdminProductCategoruEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategoru
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            # field.help_text = ''

class AdminProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from authapp.models import ShopUser
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test
from mainapp.models import ProductCategoru, Product
from django.contrib.auth.decorators import user_passes_test
from adminapp.forms import AdminShopUserRegisterForm, AdminShopUserChangeForm
import django.forms as forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from adminapp.forms import AdminShopUserRegisterForm, AdminShopUserChangeForm, AdminProductCategoruEditForm, AdminProductEditForm
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'админка/пользователи'
        return context

def user_create(request):
    if request.method == 'POST':
        form = AdminShopUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:index'))
    else:
        form = AdminShopUserRegisterForm()

    context = {
        'title': 'пользователи/создание',
        'form': form,
    }

    return render(request, 'adminapp/user_update.html', context)


def user_update(request, pk):
    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        form = AdminShopUserChangeForm(request.POST, request.FILES, instance=edit_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:user_update',
                                                kwargs={
                                                    'pk': edit_user.pk,
                                                }))
    else:
        form = AdminShopUserChangeForm(instance=edit_user)

    content = {
        'title': 'пользователи/редактирование',
        'form': form
    }

    return render(request, 'adminapp/user_update.html', content)


def user_delete(request, pk):
    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:index'))

    context = {
        'title': 'пользователи/удаление',
        'user_to_delete': user
    }

    return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda x: x.is_superuser)
def categories(request):
    categories_list = ProductCategoru.objects.all()
    context = {
        'title': 'админка/категории',
        'object_list': categories_list,
    }
    return render(request, 'adminapp/categories.html', context)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCategoruUpdateView(UpdateView):
    model = ProductCategoru
    success_url = reverse_lazy('admin:categories')
    form_class = AdminProductCategoruEditForm


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCategoruCreateView(CreateView):
    model = ProductCategoru
    success_url = reverse_lazy('admin:categories')
    form_class = AdminProductCategoruEditForm



@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCategoruDeleteView(DeleteView):
    model = ProductCategoru
    success_url = reverse_lazy('admin:categories')
    #template_name = 'adminapp/category_delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.product_set.all().update(is_active=False)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())




@user_passes_test(lambda x: x.is_superuser)
def products(request, pk):
    category = get_object_or_404(ProductCategoru, pk=pk)
    object_list = Product.objects.filter(category__pk=pk).order_by('-is_active', 'name')

    content = {
        'title': 'админка/продукт',
        'category': category,
        'object_list': object_list,
    }

    return render(request, 'adminapp/products.html', content)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductDetailView(DetailView):
    model = Product


def product_create(request, pk):
    title = 'продукт/создание'
    category = get_object_or_404(ProductCategoru, pk=pk)

    if request.method == 'POST':
        form = AdminProductEditForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        form = AdminProductEditForm(initial={'category': category})

    context = {
        'title': title,
        'form': form,
        'category': category
    }

    return render(request, 'adminapp/product_update.html', context)

def product_update(request, pk):
    title = 'продукт/создание'
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        form = AdminProductEditForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:products',
                                                kwargs={
                                                    'pk': product.category.pk
                                                }))
    else:
        form = AdminProductEditForm(instance=product)

    context = {
        'title': title,
        'form': form,
        'category': product.category,
    }

    return render(request, 'adminapp/product_update.html', context)

def product_delete(request, pk):
    item = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        item.is_active = False
        item.save()
        return HttpResponseRedirect(reverse('admin:products',
                                            kwargs={
                                                'pk': item.category.pk
                                            }))

    context = {
        'title': 'продукты/удаление',
        'object': item,
    }

    return render(request, 'adminapp/product_delete.html', context)

geekshop/django2.0/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/stil.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Cormorant+SC" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="admin_container">

           <h3 class="adminka"> Админка </h3>

        {% block menu %}
            <div class="admin_menu menu-head">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        {% endblock %}


        {% block container %}

        {% endblock %}

	</div>
</body>
</html>

geekshop/django2.0/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="categories_list">

			<a href="{% url 'admin:category_create' %}" class="button6 margin1">новая категория</a>

		
		{% for object in object_list %}
			<div class="category_record {% if not object.is_active %}not_active{% endif %}">
				<div class="category_name2">
					{{ object.name|title }}
				</div>
				<div class="category_desc">
					{{ object.description|title }}
				</div>
				<div class="category_actions">

						<a href="{% url 'admin:products' object.pk %}" class="button6" >товары категории</a>


						<a href="{% url 'admin:category_update' object.pk %}" class="button6">редактировать</a>


						<a href="{% url 'admin:category_delete' object.pk %}" class="button6">удалить</a>

				</div>

			</div>
		{% endfor%}
	</div>
{% endblock %}

geekshop/django2.0/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="user_delete user_record marg_0">
        Уверены, что хотите удалить <b>{{ object.name }}</b>?
        <div class="knop">
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger button6" type="submit" value="удалить">
        </form>

        <a href="{% url 'admin:products' object.category.pk %}" class="btn btn-success button6">отмена</a>
             </div>
    </div>
{% endblock %}

geekshop/django2.0/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'admin:products' category.pk %}" class="btn btn-round form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

geekshop/django2.0/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="products_list">

			<a href="{% url 'admin:product_create' category.pk %}" class="button4">новый товар</a>

		
		{% for object in object_list %}
			<div class="category_record margin1 {% if not object.is_active %}not_active{% endif %}">
				<img src="/media/{{ object.image|default:'products_images/tovar_promo.jpg' }}" alt="{{ object.name }}" class="admin_img">
				<div class="category_name2">
					{{ object.name|title }}
				</div>
				<div class="category_actions ">

						<a href="{% url 'admin:product_read' object.pk %}" class="button6 margin0">подробнее</a>


						<a href="{% url 'admin:product_update' object.pk %}" class="button6 margin0">редактировать</a>


						<a href="{% url 'admin:product_delete' object.pk %}" class="button6 margin0">удалить</a>

				</div>
				<div class="category_desc razmer_text margin0">
					<b>Цена:</b>
					<p>{{ object.price }} руб</p>
					<b>Количество: </b>
					<p>{{ object.quantity }}</p>
				</div>
				<div class="category_desc razmer_text margin0">
					{{ object.short_desc|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

geekshop/django2.0/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block container %}
    <div class="user_delete user_record marg_0">
       <p> Уверены, что хотите удалить <b>{{ user_to_delete.username }} {% if user_to_delete.first_name %}
                    ({{ user_to_delete.first_name|title }}</b>
                    {% if user_to_delete.last_name %}
                        {{ user_to_delete.last_name|title }}
                    {% endif %})
                {% endif %}? </p>
        <div class="knop">
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger button6 " type="submit" value="удалить">
        </form>

        <a href="{% url 'admin:index' %}" class="btn btn-success button6">отмена</a>
            </div>
    </div>
{% endblock %}

geekshop/django2.0/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="login, admin">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>

        <a href="{% url 'admin:index' %}" class="btn btn-round form-control last">
            к списку пользователей
        </a>
    </div>

{% endblock %}

geekshop/django2.0/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tag %}

{% block container %}

    <div class="users_list">

			<a href="{% url 'admin:user_create' %}" class="button4">новый пользователь</a>

		{% for object in object_list %}
			<div class="user_record {% if not object.is_active %}not_active{% endif %}">
				<img class="admin_img" src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}" alt="{{ object.username }}">
				<div class="user_role">
					{% if object.is_superuser %}администратор{% else %}пользователь{% endif %}
						<a href="{% url 'admin:user_update' object.pk %}" class="button5">редактировать</a>
						<a href="{% url 'admin:user_delete' object.pk %}" class="button5">удалить</a>
				</div>
			<div class="polzov">
				<div class="user_name ">
					<p>
						<strong>{{ object.username }}</strong>
					</p>
					<p>
					{% if object.first_name %}
						<b>{{ object.first_name|title }}</b>
						{% if object.last_name %}
							<p>{{ object.last_name|title }}</p>
						{% endif %}
					{% endif %}
					</p>
				</div>
				<div class="user_age ">
					age:<br>
					{{ object.age }} лет
				</div>
				<div class="user_email ">
					email:<br>
					{{ object.email }}
				</div>
				<div class="user_lastlogin ">
					logged:<br>
					{{ object.last_login }}
				</div>
					</div>
			</div>
		{% endfor%}
	</div>

{% endblock %}