geekshop/authapp/urls.py
import authapp.views as authapp
from django.urls import path, re_path
app_name = 'authapp'

urlpatterns = [
    re_path('^login/$', authapp.userlogin, name='login'),
    re_path('^logout/$', authapp.userlogout, name='logout'),
    re_path('^register/$', authapp.user_register, name='register'),
    re_path('^update/$', authapp.user_update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path, re_path
app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.index, name='main'),
    re_path('^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    re_path('^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    re_path('^edit/(?P<product_pk>\d+)/(?P<quantity>\d+)/ajax/$', basketapp.basket_edit),
]

geekshop/django2.0/mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path, re_path
app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.main,  name='main'),
    re_path(r'^product/', mainapp.catalog, name='catalog'),
    re_path(r'^colls/', mainapp.colls, name='colls'),
    re_path(r'^training/', mainapp.training, name='training'),
    re_path(r'^catalog/category/(\d+)/$', mainapp.catalog, name='category'),
    re_path('^catalog/category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.catalog, name='category'),
    re_path(r'^catalog/product/(?P<pk>\d+)/$', mainapp.product, name='product'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   # path('admin/', admin.site.urls),
    re_path('^', include('mainapp.urls', namespace='main')),
    re_path('^auth/', include('authapp.urls', namespace='auth')),
    re_path('^basket/', include('basketapp.urls', namespace='basket')),
    re_path('^myadmin/', include('adminapp.urls', namespace='admin')),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path('^orders/', include('ordersapp.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path, re_path
app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.main,  name='main'),
    re_path(r'^product/', mainapp.catalog, name='catalog'),
    re_path(r'^colls/', mainapp.colls, name='colls'),
    re_path(r'^training/', mainapp.training, name='training'),
    re_path(r'^catalog/category/(\d+)/$', mainapp.catalog, name='category'),
    re_path('^catalog/category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.catalog, name='category'),
    re_path(r'^catalog/product/(?P<pk>\d+)/$', mainapp.product, name='product'),
]

geekshop/django2.0/mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategoru(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True, null=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f'ProductCategoru: {self.name} ({self.pk})'


class Product(models.Model):
    category = models.ForeignKey(ProductCategoru, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', null=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64, blank=True)
    description = models.TextField(verbose_name='подробное описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f'Product: {self.name} ({self.pk})'

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategoru(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True, null=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f'ProductCategoru: {self.name} ({self.pk})'


class Product(models.Model):
    category = models.ForeignKey(ProductCategoru, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', null=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64, blank=True)
    description = models.TextField(verbose_name='подробное описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return f'{self.category.name}: {self.name}'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category__name', 'name')

geekshop/django2.0/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategoru, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random

def get_basket(user):
    if user.is_authenticated:
        return user.basket_set.all().order_by('product__category')
    return []

def main(request, category_pk=None):
    products = Product.objects.filter(category=2, is_active=True)
    products2 = Product.objects.filter(category=4, is_active=True)
    context = {
        'title': 'главная',
        'products': products,
        'products2': products2,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', context)


def colls(request):
    context = {
        'title': 'контакты',
        'colls': colls,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/colls.html', context)


def catalog(request, pk=None, page=1):
    categories = ProductCategoru.objects.filter(is_active=True)
    if pk:
        if pk == "0":
            products = Product.objects.filter(is_active=True)
            products_paginator = Paginator(products, 8)
            try:
                products = products_paginator.get_page(page)
            except PageNotAnInteger:
                products = products_paginator.get_page(1)
            except EmptyPage:
                products = products_paginator.get_page(products_paginator.num_pages)
        else:
            products = Product.objects.filter(category__pk=pk, is_active=True)
            products_paginator = Paginator(products, 3)
            try:
                products = products_paginator.get_page(page)
            except PageNotAnInteger:
                products = products_paginator.get_page(1)
            except EmptyPage:
                products = products_paginator.get_page(products_paginator.num_pages)
        context = {
            'title': 'каталог',
            'products': products,
            'categories': categories,
            'basket': get_basket(request.user),
            'category_pk': pk,

        }
        return render(request, 'mainapp/product_list.html', context)
    else:
        #products = Product.objects.all()
        #products = Product.objects.filter(category=5)
        categories = ProductCategoru.objects.filter(is_active=True)
        products = Product.objects.filter(is_active=True)
        hot_product = random.choice(products)
        same_products = Product.objects.filter(category=hot_product.category, is_active=True). \
            exclude(pk=hot_product.pk)
        context = {
            'title': 'каталог',
            'categories': categories,
            'products': products,
            'basket': get_basket(request.user),
            'hot_product': hot_product,
            'same_products': same_products,

        }
        return render(request, 'mainapp/catalog.html', context)

def product(request, pk):
    categories = ProductCategoru.objects.filter(is_active=True)
    context = {
        'title': 'продукты',
        'categories': categories,
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', context)


def training(request):
    context = {
        'page_title': 'доставка',
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/training.html', context)

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategoru, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random


def main(request, category_pk=None):
    products = Product.objects.filter(category=2, is_active=True)
    products2 = Product.objects.filter(category=4, is_active=True)
    products3 = Product.objects.filter(category=3, is_active=True)
    context = {
        'title': 'главная',
        'products': products,
        'products2': products2,
        'products3': products3,
    }
    return render(request, 'mainapp/index.html', context)


def colls(request):
    context = {
        'title': 'контакты',
        'colls': colls,
    }
    return render(request, 'mainapp/colls.html', context)


def catalog(request, pk=None, page=1):
    categories = ProductCategoru.objects.filter(is_active=True)
    if pk:
        if pk == "0":
            products = Product.objects.filter(is_active=True)
            products_paginator = Paginator(products, 12)
            try:
                products = products_paginator.get_page(page)
            except PageNotAnInteger:
                products = products_paginator.get_page(1)
            except EmptyPage:
                products = products_paginator.get_page(products_paginator.num_pages)
        else:
            products = Product.objects.filter(category__pk=pk, is_active=True)
            products_paginator = Paginator(products, 3)
            try:
                products = products_paginator.get_page(page)
            except PageNotAnInteger:
                products = products_paginator.get_page(1)
            except EmptyPage:
                products = products_paginator.get_page(products_paginator.num_pages)
        context = {
            'title': 'каталог',
            'products': products,
            'categories': categories,
            'category_pk': pk,

        }
        return render(request, 'mainapp/product_list.html', context)
    else:
        categories = ProductCategoru.objects.filter(is_active=True)
        products = Product.objects.filter(is_active=True)
        hot_product = random.choice(products)
        same_products = Product.objects.filter(category=hot_product.category, is_active=True). \
            exclude(pk=hot_product.pk)
        context = {
            'title': 'каталог',
            'categories': categories,
            'products': products,
            'hot_product': hot_product,
            'same_products': same_products,

        }
        return render(request, 'mainapp/catalog.html', context)

def product(request, pk):
    categories = ProductCategoru.objects.filter(is_active=True)
    context = {
        'title': 'продукты',
        'categories': categories,
        'product': get_object_or_404(Product, pk=pk),
    }

    return render(request, 'mainapp/product.html', context)


def training(request):
    context = {
        'page_title': 'доставка',
    }
    return render(request, 'mainapp/training.html', context)

geekshop/django2.0/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
{% block css %}
<link rel="stylesheet" href="{% static 'css/stil.css' %}">
<link href="https://fonts.googleapis.com/css?family=Cinzel|Cormorant+SC" rel="stylesheet">
<link rel="stylesheet" href="{% static 'fonts/fonts.css' %}">
{% endblock %}
{% block js %}
{% endblock %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
             ToyRoom | {{ title.title }}
        {% endblock %}
    </title>
</head>

<body>
    <div class="conteinerm-site">
        <div class="top">
            <div class="contair"></div>
            {% block container %}
            {% endblock %}
        </div>

        {% block footer %}
        <div class="footer">
            <div class="tex-foot">
                <p class="foot colore2">Все права защищены &#64; KARSAKOVA</p>
                <p class="foot"> <a class="colore" href="https://vk.com/public173903545" target="_blank">Группа ВК: https://vk.com/public173903545</p>
            </div>
        </div>
        {% endblock %}
    </div>
</body>

</html>

geekshop/django2.0/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}

<div class="top">
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <div class="slider5">
        {% include 'mainapp/includes/inc__product_menu.html' %}
        <div class="categ">

            {% if hot_product %}
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<a href="/media/{{ hot_product.image }}" target="_blank"><img class="img-cat2 photo" src="/media/{{ hot_product.image }}" ></a>
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="/media/{{ hot_product.image }}" target="_blank"><img class="img-cat5" src="/media/{{ hot_product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="/media/{{ hot_product.image }}" target="_blank"><img class="img-cat5" src="/media/{{ hot_product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="/media/{{ hot_product.image }}" target="_blank"><img class="img-cat5" src="/media/{{ hot_product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
                    <h3 class="red_hot">горячее предложение</h3>
                    <div class="nam_s">
					<h3 class="zag_product">{{ hot_product.name }}</h3>
                    <div class="text_product">
						{{hot_product.short_desc}}
					</div>
					<p class="text_product"> {{ hot_product.price }} <span>руб</span></p>

					<a href="{% url 'basket:add' hot_product.pk %}" class="button bott">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
</div>
				</div>
			</div>

			<div class="related">
				<div class="producty_cat">
					<h2>Похожие продукты</h2>
					<a class="producty_cat" href="{% url 'main:product' hot_product.pk %}">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for product in same_products %}
						<div class="block3">
							<a class="decor" href="{% url 'main:product' product.pk %}"><img class="img_hot_pr" src="/media/{{ product.image|default:'products_images/tovar_promo.jpg' }}" alt="">
							<!--<a href="#"><img src="{#{ product.image.url }#}" alt="">-->
								<div class="text">
									<h4 class="text-descr">{{ product.name }}</h4>
								</div>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		{% endif %}

        </div>
    </div>
</div>
{% endblock %}

geekshop/django2.0/mainapp/templates/mainapp/colls.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
         {% include 'mainapp/includes/inc__main_menu.html' %}
            <div class="call">
               <div class="bl">
                <h2 class="cal-t">Связаться с нами по телефонам:</h2>
                <h3 class="cal_t_2"> • 89045103710</h3>
                <h3 class="cal_t_2"> • 89006304114</h3>
                <h2 class="cal-t">Группа в ВК:</h2>
                <h3 class="cal_t_2"> <a class="colore" href="https://vk.com/public173903545" target="_blank">Toy Room - вязаные игрушки ручной работы.</a></h3>
                <h2 class="cal-t">Электронная почта:</h2>
                <h3 class="cal_t_2">toy-room18@yandex.ru </h3>
                </div>
            </div>
{% endblock %}

geekshop/django2.0/mainapp/templates/mainapp/hot_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

geekshop/django2.0/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}

    <div class="top">
        <div class="contair">
            {% include 'mainapp/includes/inc__main_menu.html' %}
            <div class="slider1">
                <div class="text4">
                    <h2 class="h2-sl">Приветствуем вас в&nbsp;нашей мастерской!</h2>
                    <p class="sl_1_t"> Здесь вы&nbsp;найдёте игрушки, сувениры и&nbsp;предметы декора, которые украсят вашу жизнь новыми красками и&nbsp;эмоциями. <br><br> Заглянув в&nbsp;каждый раздел, вы&nbsp;сможете подобрать душевный, уютный подарок для себя и&nbsp;своих близких.
                    </p>
                </div>
                <div class="imeg">
                </div>
            </div>
            <div class="slider2">
                <div class="cat2">
                    <div class="hot_list">
                        <div class="hot">
                            <a href="{% url 'main:category' 3 %}"><img class="hot" src="{% static '/img/игрушки.png' %}" alt=""> </a>
                        </div>
                        <div class="hot">
                            <a href="{% url 'main:category' 2 %}"><img class="hot" src="{% static '/img/куклы.png' %}" alt=""> </a>
                        </div>
                        <div class="hot">
                            <a href="{% url 'main:category' 4 %}"><img class="hot" src="{% static '/img/подарки.png' %}" alt=""> </a>
                        </div>
                        <div class="hot">
                            <a href="{% url 'main:category' 5 %}"><img class="hot" src="{% static '/img/распродажа.png' %}" alt=""> </a>
                        </div>
                    </div>
                    <div class="tex">
                        <h2 class="h2">Подборка лучших товаров</h2>
                    </div>
                    <div class="main_catalog">
                        {% for product in products %}

                        <a href="{% url 'main:product' product.pk %}" class="tov-cat mar"><img class="img-cat" src="/media/{{ product.image }}" alt="tovar_1">
                            {{ product.category.name }}<br>{{ product.name }}<br>
                            <h2>{{ product.price }}</h2>
                        </a>
                        {% endfor %}
                        {% for product in products2 %}
                        <a href="{% url 'main:product' product.pk %}" class="tov-cat mar"><img class="img-cat" src="/media/{{ product.image }}" alt="tovar_1">
                            {{ product.category.name }}<br>{{ product.name }}<br>
                            <h2>{{ product.price }}</h2>
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/django2.0/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    {% include 'mainapp/includes/inc__main_menu.html' %}
        <div class="dinamic_prod">
            <img class="img-cat2" src="/media/{{ product.image }}"><br>
            <div class="t_prod">
                <h3 class="zag_product">{{ product.name }}</h3><br>
            <p class="text_product">{{ product.description }}</p><br>
            <p class="text_product">{{ product.price }}<span>руб.</span></p><br>
            <a href="{% url 'basket:add' product.pk %}" class="button">
                Заказать
                <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a><br>
            <a href="{% url 'main:catalog' %}" class="button_katalog">
                в каталог
                <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
                </div>
        </div>
{% endblock %}

geekshop/django2.0/mainapp/templates/mainapp/product_list.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block container %}
    {% include 'mainapp/includes/inc__main_menu.html' %}
    {% include 'mainapp/includes/inc__product_menu.html' %}
        <div class="product_list">
            <h2 class="h2-sl5">Выбрана категория: "{% if request.resolver_match.url_name == 'category' and request.resolver_match.args.0 == '0' %}Все{% else %}{{ products.0.category.name|title }}{% endif %}"</h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'main:category' category_pk products.previous_page_number %}" class="ssylky"><</a>
                    {% endif %}
                    <span class="current">
                    страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'main:category' category_pk products.next_page_number %}" class="ssylky">></a>
                    {% endif %}
                </div>
            <div class="prod-cat">
                {% for product in products %}
                <div class="prod-cat">
                    <a href="{% url 'main:product' product.pk %}" class="tov-cat"><img class="img-cat" src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.description }} </p>
                        <h4>{{ product.price }} руб</h4>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

geekshop/django2.0/mainapp/templates/mainapp/training.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="conteinerm-site">
        <div class="top">
            {% include 'mainapp/includes/inc__main_menu.html' %}
            <div class="train">
                <img src="{% static '/img/car.png' %}" alt="fd" height="200px">
                <h2 class="text_training">Доставка осуществляется почтой Росии в&nbsp;любой город. <br> <br>Для того, чтобы уточнить,
                    какой будет конечная стоимость отправки, вам необходимо связаться с&nbsp;нами любым способом, указанным в&nbsp;разделе &laquo;Контакты&raquo;.
                    <br><br> Мы&nbsp;можем сразу празднично упаковать ваш подарок. Стоимость: 200&nbsp;рублей. <br><br>
                    Возможен самовывоз из&nbsp;г.Выборг.</h2>
            </div>
        </div>
    </div>
{% endblock %}